### ISSUE TITLE
Не устанавливается локально

### ISSUE THREAD

**Issue by ghost** [senior-sigan/KawaiiSearch#2]
В файле requirements.txt указаны зависимости без версий, сейчас не удается запустить локально, подскажите, пожалуйста, версии с которыми проект работал

**Comment by senior-sigan** [comment]
@skulaga-angelsit Добрый день.
Да, зря я 5 лет назад не зафиксировал версии библиотек. Но уверен, что сейчас были бы проблемы с keras и tensorflow-1.
Посмотрите лучше вот этот [джупитер ноутбук](https://colab.research.google.com/drive/1l2klkhq2IrsF2mn3YrqwDBLLkk_ug9Q2?usp=sharing), который я делал для мастер-класса по поиску картинок. Он более менее свежий, там pytorch.

Сейчас State-of-the-art для поиска похожих это взять CLIP для получение представлений и использовать косинусное расстояние.

**Comment by ghost** [comment]
спасибо
